name: Test

on:
  pull_request:
    branches:
      - main

jobs:
  go-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - run: go test -coverprofile=cover.out -v ./...
      - uses: deepsourcelabs/test-coverage-action@v1
        with:
          key: go
          coverage-file: cover.out
          dsn: ${{ secrets.DEEPSOURCE_DSN }}
